[package]
name = "pangya-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
pangya-crypto = { version = "0.1.0", path = "../pangya-crypto" }
pangya-domain = { version = "0.1.0", path = "../pangya-domain" }
thiserror.workspace = true
tokio-util.workspace = true
zeroize.workspace = true

[dev-dependencies]
proptest.workspace = true
tokio.workspace = true

[lints]
workspace = true
