[package]
name = "pangya-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
cap-std.workspace = true
clap.workspace = true
config.workspace = true
humantime.workspace = true
pangya-admin = { version = "0.1.0", path = "../pangya-admin" }
pangya-data = { version = "0.1.0", path = "../pangya-data" }
pangya-domain = { version = "0.1.0", path = "../pangya-domain" }
pangya-game = { version = "0.1.0", path = "../pangya-game" }
pangya-login = { version = "0.1.0", path = "../pangya-login" }
pangya-message = { version = "0.1.0", path = "../pangya-message" }
pangya-observability = { version = "0.1.0", path = "../pangya-observability" }
pangya-protocol = { version = "0.1.0", path = "../pangya-protocol" }
pangya-storage = { version = "0.1.0", path = "../pangya-storage" }
pangya-updater = { version = "0.1.0", path = "../pangya-updater" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
zeroize.workspace = true

[dev-dependencies]
pangya-crypto = { version = "0.1.0", path = "../pangya-crypto" }
tracing-subscriber.workspace = true
uuid.workspace = true

[lints]
workspace = true
